name: SpigotBlankPlugin
main: com.cole.blankplugin.SpigotPluginBlank
version: 1.0
api-version: 1.21
commands:
  waterlevel:
    description: changes the water level
    usage: /waterlevel <level>
    arguments:
      level:
        type: integer
        description: the new water level
  autoupdate:
    description: enable or disable terrain auto updating
    usage: /autoupdate <state>
    arguments:
      state:
        type: string
        description: the new state (on/off)
  timer:
    description: set timer for auto update
    usage: /timer <seconds>
    arguments:
      seconds:
        type: integer
        description: time in seconds
  default:
    description: restores settings to default values
    usage: /default
  scale:
    description: scale resolution of rendered terrain
    usage: /scale <length>
    arguments:
      type: integer
      description: length in blocks of new scaled x dimension
  fastrender:
    description: enable or disable optimized rendering
    usage: /fastrender <state>
    arguments:
      state:
        type: string
        description: the new state (on/off)
