name: Maven Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'plugin/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 20 (using Temurin)
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '20'

      # Build the project using Maven from the /plugin directory.
      - name: Build with Maven
        working-directory: plugin
        run: mvn clean package

      # Ensure plugins directory exists
      - name: Ensure plugins directory exists
        run: mkdir -p launcher/server/plugins
      
      - name: Rename JAR to KinectSandbox.jar
        run: mv plugin/target/KinectSandbox-0.0.1-SNAPSHOT.jar plugin/target/KinectSandbox.jar

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository again (necessary for the release job)
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up GitHub CLI to create a release
      - name: Set up GitHub CLI
        uses: cli/cli-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Create GitHub Release
      - name: Create GitHub Release
        run: |
          RELEASE_TAG="v$(date +'%Y%m%d%H%M%S')"  # Generate a timestamp-based version
          gh release create $RELEASE_TAG \
            plugin/target/KinectSandbox.jar \
            --title "KinectSandbox Release $RELEASE_TAG" \
            --notes "Built by build-jar-release.yml" \
            --draft

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: List releases
        run: gh release list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
