name: Maven Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'plugin/**'
      - '.github/workflows/*.yml' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 20 (using Temurin)
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '20'

      # Build the project using Maven from the /plugin directory.
      - name: Build with Maven
        working-directory: plugin
        run: mvn clean package

      # Ensure plugins directory exists
      - name: Ensure plugins directory exists
        run: mkdir -p launcher/server/plugins

      # Copy the built JAR from the target directory to the desired location.
      - name: Copy JAR to plugins directory
        working-directory: plugin
        run: cp target/KinectSandbox-0.0.1-SNAPSHOT.jar ../launcher/server/plugins/KinectSandbox.jar

      # Create a new tag for the release
      - name: Create a new tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Generate a tag based on the current timestamp
          git tag $TAG_NAME
          git push origin $TAG_NAME
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Create GitHub Release and upload the JAR to the release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: launcher/server/plugins/KinectSandbox.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
