
name: Maven Build and Deploy

on:
  push:
    branches:
      - main/plugin

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 20 (using Temurin)
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '20'

      # Build the project using Maven. This runs all phases including package.
      - name: Build with Maven
        run: mvn clean package

      # Copy the built JAR from the target directory to the desired location.
      - name: Copy final JAR to plugins directory
        run: cp target/KinectSandbox-0.0.1-SNAPSHOT.jar MC-AR-Sandbox/launcher/server/plugins/KinectSandbox.jar
