name: Maven Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'plugin/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK 20 (using Temurin)
      - name: Set up JDK 20
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '20'

      # Build the project using Maven from the /plugin directory.
      - name: Build with Maven
        working-directory: plugin
        run: mvn clean package

      # Copy the built JAR from the target directory to the desired location.
      # Here, we assume that the target JAR is located at plugin/target and that
      # MC-AR-Sandbox/launcher/server/plugins is at the repository root.
      - name: Ensure plugins directory exists
        run: mkdir -p launcher/server/plugins
      
      - name: Copy JAR to plugins directory
        working-directory: plugin
        run: cp target/KinectSandbox-0.0.1-SNAPSHOT.jar ../launcher/server/plugins/KinectSandbox.jar

